name: ConnectUs
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.0.0
  split_button: ^0.1.0
  file_picker: ^10.3.2
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  flutter_screenutil: ^5.9.3
  flutter_contacts: ^1.1.9+2
  logger: ^2.6.1
  image_picker: ^1.0.7
  flutter_dotenv: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animated_text_kit: ^4.2.3
  url_launcher: ^6.3.2
  flutter_webrtc: ^1.1.0
  avatar_glow: ^3.0.1
  langchain: ^0.8.0+1
  langchain_ollama: ^0.4.0+1
  langchain_openai: ^0.8.0+1
  socket_io_client: ^2.0.3
  encrypt: ^5.0.3
  provider: ^6.1.5+1

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.9

flutter:
  assets:
    - assets/images/
    - assets/.env

  uses-material-design: true

  fonts:
    - family: EduNSWACTCursive
      fonts:
        - asset: assets/fonts/EduNSWACTCursive-VariableFont_wght.ttf
